# Generated by Django 5.0.3 on 2024-07-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('drinks', 'Drinks'), ('dessert', 'Dessert')], default='lunch', max_length=10),
        ),
    ]
