# Generated by Django 5.0.3 on 2024-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
