# Generated by Django 5.0.3 on 2024-08-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_caregory_category_blog_caregory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='caregory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.category'),
        ),
    ]
