# Generated by Django 5.0.3 on 2024-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='blogs', to='blog.tags'),
        ),
    ]
