# Generated by Django 5.0.3 on 2024-08-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='caregory',
            new_name='category',
        ),
    ]
